terrascope/__init__.py
from .app import create_app

terrascope/app.py
import os
from flask import Flask
import logging

import terrascope.config
import terrascope.db
import terrascope.services.visualizer
import terrascope.services.world_listener
from .config import BaseConfig
from .frontend import frontend
from .utils import INSTANCE_FOLDER_PATH, pretty_date
from .api import snapshots

# For import *
__all__ = ["create_app"]

DEFAULT_BLUEPRINTS = (frontend, snapshots.blueprint)


def create_app(config=None, app_name=None, blueprints=None):
    # Create a Flask app
    if app_name is None:
        app_name = BaseConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(
        app_name, instance_path=INSTANCE_FOLDER_PATH, instance_relative_config=True
    )

    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_template_filters(app)
    configure_error_handlers(app)

    logging.basicConfig(level=logging.DEBUG)
    terrascope.db.init(app)
    terrascope.services.world_listener.init(
        app, terrascope.services.visualizer.visualize
    )
    terrascope.services.visualizer.init(app)

    return app


def configure_app(app: Flask, config: terrascope.config.BaseConfig = None):
    # apply the default config
    app.config.from_object(BaseConfig)
    # apply custom modifications next
    if config:
        app.config.from_object(config)
    # allow overlaying the config using env variables
    for v in vars(BaseConfig):
        if v in os.environ:
            cls = type(getattr(BaseConfig, v))
            app.config[v] = cls(os.environ[v])

    # sanity checks
    if app.config["SECRET_KEY"] == "":
        raise RuntimeError(
            "'SECRET_KEY' was not provided in the configuration. "
            "This must be set to a long random bytestring. You can generate one by running: "
            "python -c 'import secrets; print(secrets.token_hex())'"
        )
    if app.config["TERRASCOPE_DATA_DIRECTORY"] == "":
        raise RuntimeError(
            "'TERRASCOPE_DATA_DIRECTORY' was not provided in the configuration. "
            "This must point to a folder somewhere on the filesystem where database "
            "and captures will be stored at."
        )


def configure_blueprints(app, blueprints):
    # Configure blueprints in views
    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):
    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format="%Y-%m-%d"):
        return value.strftime(format)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):
    @app.errorhandler(403)
    def forbidden_page(error):
        return "Oops! You don't have permission to access this page.", 403

    @app.errorhandler(404)
    def page_not_found(error):
        return "Opps! Page not found.", 404

    @app.errorhandler(500)
    def server_error_page(error):
        return "Oops! Internal server error. Please try after sometime.", 500

terrascope/frontend/__init__.py
from .views import frontend

terrascope/frontend/views.py
from flask import (Blueprint, render_template)

frontend = Blueprint('frontend', __name__)

@frontend.route('/')
def index():
    return render_template('frontend/landing.html', _active_home=True)

terrascope/templates/frontend/landing.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Terrascope' %}

{% extends 'layouts/base.html' %}

{% block body %}

<div class="container">
  <div id="map"></div>
</div>

<script>
  const map = L.map('map', {
    crs: L.CRS.Simple,
    minZoom: -5,
  }).setView([0, 0], 0);

  async function fetchSnapshots() {
    const response = await fetch('/api/v1/snapshots');
    return response.json();
  }

  function groupSnapshotsByWorld(snapshots) {
    const byWorldName = snapshots.reduce((groups, snapshot) => {
      const worldName = snapshot.world_name;
      if (!groups[worldName]) {
        groups[worldName] = [];
      }
      groups[worldName].push(snapshot);
      return groups;
    }, {});
    for (const world in byWorldName) {
      byWorldName[world].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
    }
    return byWorldName;
  }

  function switchToSnapshot(snapshot) {
    const dropdownButton = document.getElementById('snapshotDropdown');

    // FIXME: Update with up-to-date snapshot dimensions
    const imageBounds = [[0, 0], [2400, 8400]];
    const imageUrl = `/api/v1/snapshot/${snapshot.id}/image`;
    changeMapImage(imageUrl, imageBounds);
    dropdownButton.textContent = `${snapshot.world_name} - ${new Date(snapshot.timestamp).toLocaleString()}`
  }

  async function populateSnapshotList() {
    try {
      const snapshots = await fetchSnapshots();
      const groupedSnapshots = groupSnapshotsByWorld(snapshots);

      const dropdown = document.getElementById('snapshotList');
      dropdown.innerHTML = '';

      for (const worldName in groupedSnapshots) {
        const headerItem = document.createElement('li');
        headerItem.innerHTML = `<h6 class="dropdown-header">${worldName}</h6>`;
        dropdown.appendChild(headerItem);

        groupedSnapshots[worldName].forEach(snapshot => {
          const listItem = document.createElement('li');
          listItem.innerHTML = `<a class="dropdown-item" href="#" data-snapshot-id="${snapshot.id}">${new Date(snapshot.timestamp).toLocaleString()}</a>`;
          dropdown.appendChild(listItem);

          listItem.addEventListener('click', (event) => {
            event.preventDefault();
            switchToSnapshot(snapshot);
          });
        });
      }

      const latestSnapshot = snapshots.reduce((latest, snapshot) => {
        return new Date(snapshot.timestamp) > new Date(latest.timestamp) ? snapshot : latest;
      });
      switchToSnapshot(latestSnapshot);
    } catch (error) {
      console.error('Error loading snapshots:', error);
    }
  }

  async function changeMapImage(imageUrl, imageBounds) {
    try {
      map.eachLayer(function (layer) {
        if (layer instanceof L.ImageOverlay) {
          map.removeLayer(layer);
        }
      });
      L.imageOverlay(imageUrl, imageBounds).addTo(map);
      map.fitBounds(imageBounds);
    } catch (error) {
      console.error('Error loading snapshot image:', error);
    }
  }

  document.addEventListener('DOMContentLoaded', populateSnapshotList);

</script>



{% endblock %}

terrascope/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Terrascope">
  <meta name="author" content="github.com/">

  <title>{% block title %}{{ page_title|default('Terrascope') }}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename='leaflet.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename='terrascope.css')}}" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
</head>

<body>

  <!-- Leaflet -->
  <script src="{{ url_for('static', filename='leaflet.js')}}"></script>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <img class="navbar-brand" href="{{ url_for('frontend.index') }}"
        src="{{ url_for('static', filename='images/terrascope.png')}}" alt="terrascope logo">
      <a class="navbar-brand" href="{{ url_for('frontend.index') }}">
        Terrascope
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% include 'layouts/header.html'%}
    </div>
  </nav>
  {% include 'macros/_flash_msg.html' %}
  <!-- Page Content -->
  {% block body %}

  {% endblock %}

  <!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='jquery-3.7.1.slim.min.js')}}"></script>
  <script src="{{ url_for('static', filename='bootstrap.bundle.min.js')}}"></script>

</body>

</html>

terrascope/templates/layouts/header.html
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav ml-auto">
    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" id="snapshotDropdown" data-bs-toggle="dropdown"
        aria-expanded="false">
        Select a Snapshot
      </button>
      <ul class="dropdown-menu" id="snapshotList" aria-labelledby="snapshotDropdown">
        <!-- dynamically populated -->
      </ul>
    </div>
  </ul>
</div>

terrascope/templates/macros/_flash_msg.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} alert-dismissible fade show col-lg-4 offset-4 mt-3" role="alert">
    	{{ message }} <button type="button" class="close" data-dismiss="alert">×</button>
	</div>
    {% endfor %}
  {% endif %}
{% endwith %}

terrascope/templates/macros/_form.html
{% macro render_checkbox(field) %}
<div class="checkbox{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id }}">
        {{ field }}{{ field.label.text }}
    </label>
    <span class="help-inline">{{ field.description }}</span>
    {% if field.errors -%}
    <ul class="help-block">
        {% for error in field.errors -%}
        <li>{{ error|e }}</li>
        {%- endfor %}
    </ul>
    {%- endif %}
</div>
{% endmacro%}

{% macro render_radio(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label(class_="control-label") }}
    <div class="">
        {% for subfield in field -%}
        <label for="{{ subfield.id }}" class="radio-inline">
            {{ subfield }} {{ subfield.label.text }}
        </label>
        {%- endfor %}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_datepicker(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field() }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_textarea(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field(class_="form-control", rows="4") }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_file(field) %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
    <label class="control-label" 
        for="{{ field.id }}">
        {{ field.label }}
    </label>
    <div class="">
        {{ field }}
        <span class="help-inline">{{ field.description }}</span>
        {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors -%}
            <li>{{ error }}</li>
            {%- endfor %}
        </ul>
        {%- endif %}
    </div>
</div>
{% endmacro %}

{% macro render_input(field) %}
<div class="form-group {% if field.errors %}has-danger{% endif %}">
    <label for="{{ field.id }}">{{ field.label }}</label>
    {{ field(class_="form-control") }}
    <span class="help-inline">{{ field.description }}</span>

    {% if field.errors -%}
        <ul class="help-block">
            {% for error in field.errors %}
            <label class="error mt-2 text-danger" for="{{ field.id }}">{{ error }}</label><br>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endmacro %}

{% macro render_action(field) %}
<div class="form-group">
    <div class="form-actions">
        {{ field(class_="btn btn-primary") }}
    </div>
</div>
{% endmacro %}

{% macro render_form(url, form, horizontal=False, legend=None, confirm_msg=None, formid=None) %}
{% set idattr = "id=" + formid if formid else "" %}
<form {{idattr}} class="{% if horizontal %}form-horizontal{% endif %}" method="POST" action="{{ url }}"
    {% if confirm_msg %}onsubmit='return confirm("{{ confirm_msg }}");' {% endif %} 
    {% if form.multipart %}enctype="multipart/form-data"{% endif %} >
    {{ form.hidden_tag() }}
        {% if legend %}
        <legend>{{ legend|safe }}</legend>
        {% endif %}
        {% set focus = True %}
        {% for field in form %}
            {% if field.type != "HiddenField" and field.type != "CSRFTokenField" %}
                {% if field.type == "RadioField" %}
                    {{ render_radio(field) }}
                {% elif field.type == "BooleanField" %}
                    {{ render_checkbox(field) }}
                {% elif field.type == "SubmitField" %}
                    {{ render_action(field) }}
                {% elif field.type == "TextAreaField" %}
                    {{ render_textarea(field) }}
                {% elif field.type == "DateField" %}
                    {{ render_datepicker(field) }}
                {% elif field.type == "FileField" %}
                    {{ render_file(field) }}
                {% elif field.type == "TextField" %}
                    {% if focus %}
                        {{ render_input(field) }}
                        {% set focus = False %}
                    {% else %}
                        {{ render_input(field) }}
                    {% endif %}
                {% else %}
                    {{ render_input(field) }}
                {% endif %}
            {% endif %}
        {% endfor %}
</form>
{% endmacro %}